// src/components/layout/Logo/logo_images/png/index.ts

export { default as logo_01 } from './jordanLambrecht_logo_full_01.png'
export { default as logo_02 } from './jordanLambrecht_logo_full_02.png'
export { default as logo_03 } from './jordanLambrecht_logo_full_03.png'
export { default as logo_04 } from './jordanLambrecht_logo_full_04.png'
export { default as logo_05 } from './jordanLambrecht_logo_full_05.png'
export { default as logo_06 } from './jordanLambrecht_logo_full_06.png'
export { default as logo_07 } from './jordanLambrecht_logo_full_07.png'
export { default as logo_08 } from './jordanLambrecht_logo_full_08.png'
export { default as logo_09 } from './jordanLambrecht_logo_full_09.png'
export { default as logo_10 } from './jordanLambrecht_logo_full_10.png'
export { default as logo_11 } from './jordanLambrecht_logo_full_11.png'
export { default as logo_12 } from './jordanLambrecht_logo_full_12.png'
export { default as logo_13 } from './jordanLambrecht_logo_full_13.png'
export { default as logo_14 } from './jordanLambrecht_logo_full_14.png'
export { default as logo_15 } from './jordanLambrecht_logo_full_15.png'
export { default as logo_16 } from './jordanLambrecht_logo_full_16.png'
